---
- name: start contrail analyticsdb
  docker_service:
    project_name: contrail-analyticsdb
    pull: yes
    definition:
      version: '2'
      services:
        network:
          image: docker.io/kubernetes/pause
          network_mode: "host"
          volumes:
           - /etc/hosts:/etc/hosts
        kafka:
          image: "{{ CONTAINER_REGISTRY }}/contrail-analyticsdb-kafka:{{ CONTRAIL_VERSION }}"
          network_mode: "service:network"
          env_file: /tmp/common.env
          depends_on:
            - network
          restart: on-failure
        #redis-query:
        #  image: "{{ CONTAINER_REGISTRY }}/contrail-redis-query:{{ CONTRAIL_VERSION }}"
        #  env_file: /tmp/common.env
        #  volumes:
        #    - /var/log/docker/contrail:/var/log/contrail
        #  depends_on:
        #    - network
        #  restart: on-failure
