contrail_configuration:
  CONTRAIL_VERSION: 4.1.0.0-4
  CONTROLLER_NODES: 192.168.1.100,192.168.1.101,192.168.1.102
  #CASSANDRA_SEEDS: 192.168.1.100
  CONTRAIL_VIP: 192.168.1.100
  CLOUD_ORCHESTRATOR: kubernetes
